export const metricNames = {
    'price':'Price',
    'new_marketcap':'Marketcap',
    'fee_change_1d':'Fee Change 1d',
    'fee_change_1m':'Fee Change 1m',
    'fee_change_7d':'Fee Change 7d',
    'fee_total7d':'7D fees',
    'fee_total24h':'24H fees',
    'fee_totalAllTime':'All Time fees',
    'tvl':'TVL',
    'tvl_change_1d':'TVL Change 1d',
    'tvl_change_1h':'TVL Change 1h',
    'tvl_change_7d':'TVL Change 7d',
    'all_time_high':'ATH',
    'annual_inflation_percent':'Annual Inflation Percent',
    'circulating_supply':'Circulating Supply',
    'cycle_low':'Cycle Low',
    'days_since_all_time_high':'Days Since ATH',
    'days_since_cycle_low':'Days Since Cycle Low',
    'github_stars':'Github Stars',
    'github_watchers':'Github Watchers',
    'liquid_marketcap_usd':'Liquid Marketcap USD',
    'liquid_supply':'Liquid Supply',
    'onchain_active_addresses':'Onchain Active Addresses',
    'onchain_addresses_count':'Onchain Addresses Count',
    'percent_change_btc_last_1_month':'% Change BTC Last 1 Month',
    'percent_change_btc_last_1_week':'% Change BTC Last 1 Week',
    'percent_change_btc_last_1_year':'% Change BTC Last 1 Year',
    'percent_change_btc_last_3_months':'% Change BTC Last 3 Months',
    'percent_change_btc_last_24_hours':'% Change BTC Last 24 Hours',
    'percent_change_eth_last_1_month':'% Change ETH Last 1 Month',
    'percent_change_eth_last_1_week':'% Change ETH Last 1 Week',
    'percent_change_eth_last_1_year':'% Change ETH Last 1 Year',
    'percent_change_eth_last_3_months':'% Change ETH Last 3 Months',
    'percent_change_eth_last_24_hours':'% Change ETH Last 24 Hours',
    'percent_change_last_1_month':'% Change Last 1 Month',
    'percent_change_last_1_week':'% 1W Change',
    'percent_change_last_1_year':'% Change Last 1 Year',
    'percent_change_last_3_months':'% Change Last 3 Months',
    'percent_change_month_to_date':'% Change Month to Date',
    'percent_change_quarter_to_date':'% Change Quarter to Date',
    'percent_change_usd_last_24_hours':'$ Change 24H',
    'percent_change_year_to_date':'% Change Year to Date',
    'percent_down_since_ath':'% Down Since ATH',
    'percent_up_since_cycle_low':'% Up Since Low',
    'price_btc':'Price BTC',
    'price_eth':'Price ETH',
    'rank':'Rank',
    'real_volume_last_24_hours':'Real Volume Last 24 Hours',
    'reddit_active_user_count':'Reddit Active User Count',
    'reddit_subscribers':'Reddit Subscribers',
    'roi_2011_usd_percent':'ROI 2011 USD Percent',
    'roi_2012_usd_percent':'ROI 2012 USD Percent',
    'roi_2013_usd_percent':'ROI 2013 USD Percent',
    'roi_2014_usd_percent':'ROI 2014 USD Percent',
    'roi_2015_usd_percent':'ROI 2015 USD Percent',
    'roi_2016_usd_percent':'ROI 2016 USD Percent',
    'roi_2017_usd_percent':'ROI 2017 USD Percent',
    'roi_2018_usd_percent':'ROI 2018 USD Percent',
    'roi_2019_usd_percent':'ROI 2019 USD Percent',
    'roi_2020_usd_percent':'ROI 2020 USD Percent',
    'roi_2021_usd_percent':'ROI 2021 USD Percent',
    'stock_to_flow':'Stock to Flow',
    'supply_active_1d':'Supply Active 1d',
    'supply_in_top_1_percent_addresses':'Supply in Top 1 Percent Addresses',
    'supply_in_top_10_percent_addresses':'Supply in Top 10 Percent Addresses',
    'supply_in_top_100_addresses':'Supply in Top 100 Addresses',
    'volume_last_24_hours':'Volume Last 24 Hours',
    'y_2050':'Y 2050',
    'y_2050_issued_percent':'Y 2050 Issued Percent',
    'y_2050_marketcap_usd':'Y 2050 Marketcap USD',
    'y_plus10':'Y Plus 10',
    'y_plus10_issued_percent':'Y Plus 10 Issued Percent',
    'y_plus10_marketcap_usd':'Y Plus 10 Marketcap USD'
  }