export const metricOptions = [
        { id: "price", label: "Price" },
        { id: "new_marketcap", label: "Marketcap" },
        { id: "fee_change_1d", label: "Fee Change 1d" },
        { id: "fee_change_1m", label: "Fee Change 1m" },
        { id: "fee_change_7d", label: "Fee Change 7d" },
        { id: "fee_total7d", label: "7D fees" },
        { id: "fee_total24h", label: "24H fees"},
        { id: "fee_totalAllTime", label: "All Time fees" }, 
        { id: "tvl", label: "TVL" }, 
        { id: "tvl_change_1d", label: "TVL Change 1d" }, 
        { id: "tvl_change_1h", label: "TVL Change 1h" }, 
        { id: "tvl_change_7d", label: "TVL Change 7d" },
        { id: "all_time_high", label: "All Time High" },
        { id: "annual_inflation_percent", label: "Annual Inflation Percent" },
        { id: "circulating_supply", label: "Circulating Supply" },
        { id: "cycle_low", label: "Cycle Low" },
        { id: "days_since_all_time_high", label: "Days Since ATH" },
        { id: "days_since_cycle_low", label: "Days Since Cycle Low" },
        { id: "github_stars", label: "Github Stars" },
        { id: "github_watchers", label: "Github Watchers" },
        { id: "liquid_marketcap_usd", label: "Liquid Marketcap USD" },
        { id: "liquid_supply", label: "Liquid Supply" },
        { id: "onchain_active_addresses", label: "Onchain Active Addresses" },
        { id: "onchain_addresses_count", label: "Onchain Addresses Count" },
        { id: "percent_change_btc_last_1_month", label: "% Change vs. BTC Last 1 Month" },
        { id: "percent_change_btc_last_1_week", label: "% Change vs. BTC Last 1 Week" },
        { id: "percent_change_btc_last_1_year", label: "% Change BTC Last 1 Year" },
        { id: "percent_change_btc_last_3_months", label: "% Change BTC Last 3 Months" },
        { id: "percent_change_btc_last_24_hours", label: "% Change BTC Last 24 Hours" },
        { id: "percent_change_eth_last_1_month", label: "% Change ETH Last 1 Month" },
        { id: "percent_change_eth_last_1_week", label: "% Change ETH Last 1 Week" },
        { id: "percent_change_eth_last_1_year", label: "% Change ETH Last 1 Year" },
        { id: "percent_change_eth_last_3_months", label: "% Change ETH Last 3 Months" },
        { id: "percent_change_eth_last_24_hours", label: "% Change ETH Last 24 Hours" },
        { id: "percent_change_last_1_month", label: "% Change Last 1 Month" },
        { id: "percent_change_last_1_week", label: "% Change Last 1 Week" },
        { id: "percent_change_last_1_year", label: "% Change Last 1 Year" },
        { id: "percent_change_last_3_months", label: "% Change Last 3 Months" },
        { id: "percent_change_month_to_date", label: "% Change Month to Date" },
        { id: "percent_change_quarter_to_date", label: "% Change Quarter to Date" },
        { id: "percent_change_usd_last_24_hours", label: "% Change USD Last 24 Hours" },
        { id: "percent_change_year_to_date", label: "% Change Year to Date" },
        { id: "percent_down_since_ath", label: "% Down Since ATH" },
        { id: "percent_up_since_cycle_low", label: "% Up Since Cycle Low" },
        { id: "price_btc", label: "Price vs. BTC" },
        { id: "price_eth", label: "Price vs. ETH" },
        { id: "real_volume_last_24_hours", label: "Real Volume Last 24 Hours" },
        { id: "reddit_active_user_count", label: "Reddit Active User Count" },
        { id: "reddit_subscribers", label: "Reddit Subscribers" },
        { id: "roi_2011_usd_percent", label: "ROI 2011 USD Percent" },
        { id: "roi_2012_usd_percent", label: "ROI 2012 USD Percent" },
        { id: "roi_2013_usd_percent", label: "ROI 2013 USD Percent" },
        { id: "roi_2014_usd_percent", label: "ROI 2014 USD Percent" },
        { id: "roi_2015_usd_percent", label: "ROI 2015 USD Percent" },
        { id: "roi_2016_usd_percent", label: "ROI 2016 USD Percent" },
        { id: "roi_2017_usd_percent", label: "ROI 2017 USD Percent" },
        { id: "roi_2018_usd_percent", label: "ROI 2018 USD Percent" },
        { id: "roi_2019_usd_percent", label: "ROI 2019 USD Percent" },
        { id: "roi_2020_usd_percent", label: "ROI 2020 USD Percent" },
        { id: "roi_2021_usd_percent", label: "ROI 2021 USD Percent" },
        { id: "stock_to_flow", label: "Stock to Flow" },
        { id: "supply_active_1d", label: "Supply Active 1d" },
        { id: "supply_in_top_1_percent_addresses", label: "Supply in Top 1 Percent Addresses" },
        { id: "supply_in_top_10_percent_addresses", label: "Supply in Top 10 Percent Addresses" },
        { id: "supply_in_top_100_addresses", label: "Supply in Top 100 Addresses" },
        { id: "volume_last_24_hours", label: "Volume Last 24 Hours" },
        { id: "y_2050", label: "Y 2050" },
        { id: "y_2050_issued_percent", label: "Y 2050 Issued Percent" },
        { id: "y_2050_marketcap_usd", label: "Y 2050 Marketcap USD" },
        { id: "y_plus10", label: "Y Plus 10" },
        { id: "y_plus10_issued_percent", label: "Y Plus 10 Issued Percent" },
        { id: "y_plus10_marketcap_usd", label: "Y Plus 10 Marketcap USD" } ]